# fly.toml app configuration file generated for towpath-4772e4a8 on 2026-08-22T14:30:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'towpath-4772e4a8'
primary_region = "sjc"

[build]
dockerfile = "Dockerfile"

[deploy]
strategy = "rolling"
wait_timeout = "10m"

[env]
POUND_ARTIFACT_PATH = "/app/artifacts/england.pkl"
POUND_CATALOG_PATH = "/app/artifacts/england-catalog.pkl"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1

[[http_service.checks]]
method = "GET"
path = "/api/health"
grace_period = "1m"
interval = "15s"
timeout = "10s"

[[vm]]
cpu_kind = "shared"
cpus = 2
memory = "4gb"
